[project]
name = "classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<=3.12"
dependencies = [
    "opencv-python>=4.11.0.86",
    "streamlit>=1.52.2",
    "tensorflow==2.15.0",
]


